"""add markdown

Revision ID: 26528dac1d8d
Revises: 6eaf69761066
Create Date: 2020-11-22 09:12:36.978386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26528dac1d8d'
down_revision = '6eaf69761066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('markdown', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'markdown')
    # ### end Alembic commands ###
