"""add ban message

Revision ID: 6eaf69761066
Revises: c538f8090689
Create Date: 2020-10-09 14:22:41.395543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eaf69761066'
down_revision = 'c538f8090689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('ban_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'ban_message')
    # ### end Alembic commands ###
